### ISSUE TITLE
Javascript styling problem

### ISSUE THREAD

**Issue by NicholasCF** [nussucommit/takoyaki#382]
I am trying to leave this as a good first issue.

Some of the javascript if-else branches are written in the wrong style (they currently work as intended though), so it may confuse people who wanted to modify them later

---
![Screen Shot 2019-10-23 at 11 10 36 AM](https://user-images.githubusercontent.com/42194963/67353774-016f3980-f586-11e9-8bd5-8f1f2d21e4b3.png)

**Comment by cdrani** [comment]
@NicholasCF: Would love to take this up. What do you mean by wrong style? Like missing enclosing braces around the if/else blocks? Here's what I had in mind for a little refactor:

```js
function sendAlert(message) {
   alert(message);
   return false;
}

function validateModal() {
  const modalChecked = !!$("#grap-drop-modal input[type=checkbox]:checked").length
  if (!modalChecked) { 
    return sendAlert("Please select at least on time slot");
  }

  return modalChecked;
}

function validateGrabPage() {
  const checked = !!$("#grab-page-form input[type=checkbox]:checked").length

  if (!checked) { 
    return sendAlert("Please select at least on time slot");
  }

  return checked;
```

The validation functions could be refactored into one function by either allowing the passing of the selector as a parameter:

```js
function validator(selector) {
  const checked = !!$(selector).length

  if (!checked) { 
    return sendAlert("Please select at least on time slot");
  }

  return checked
}
```

or keeping the possible selectors in an object and having the validator accept a key parameter:

```js
function validator(key) {
  const selectors = {
    pageForm: "#grab-page-form input[type=checkbox]:checked",
    modal: "#grap-drop-modal input[type=checkbox]:checked"
  }

  const checked = !!$(selectors[key]).length

  if (!checked) { 
    return sendAlert("Please select at least on time slot");
  }

  return checked
}
```

I am leaning towards the one singular validator function approach.
