### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by ryoarmanda** [nussucommit/takoyaki#465]
There is one particular test that keeps failing intermittently in Travis

![image](https://user-images.githubusercontent.com/24468110/77216719-7192e300-6b57-11ea-98d0-2be58d2ed6c9.png)

**Comment by chrisjwelly** [comment]
Seems to be able to pass only after 10AM in the morning..

**Comment by JQChong** [comment]
Yup, even locally :)

**Comment by ryoarmanda** [comment]
This happens again at midnight and I finally found out the reason. For future reference:

- In the test code, the Duty entry created does not have the `date` field supplied, so it takes today's date as default.
- In this particular test, the start time is 2 hours before local time, so if you're testing at 12-2 AM (on systems with local time) or 8-10 AM (on systems with UTC), the start time is actually at 10PM-12AM
- In `grabable_duties` method, one of the condition clause for the query is `date + time_ranges.start_time > Time.zone.now`. Combine the two points above will give us `Today at 10PM > Today at 12AM` which is logically true, and so the duty will be thought as "grabable"

Lesson learned: When it comes with time, don't mess around.
